### ISSUE TITLE
[BUG] Vault action for kv1(ca cert) works  but doesnt work for kv2 (ca cert)

### ISSUE THREAD

**Issue by prashant6475** [hashicorp/vault-action#104]
**Describe the bug**
Trying to retrieve secrets using master branch it works for kv1(ca cert)  but doesnt work for kv2 (ca cert)

**To Reproduce**
  steps:
     - uses: actions/checkout@v2
     - name: Import Secrets
       uses: hashicorp/vault-action@master
       with:
           url: https:/xx.xxx.xx
           token: ${{ secrets.VAULTTOKEN }}
           caCertificate: ${{ secrets.VAULT_CA }}
           #kv-version: 2
           #tlsSkipVerify: true
           secrets: secret/xxx/xx/xx

**Expected behavior**

Run hashicorp/vault-action@master
::group::Get Vault Secrets
Get Vault Secrets
  ::add-mask::***
  ::set-env name=LOGIN::***
  ##[debug]LOGIN='***'
  ::set-output name=login::***
  ##[debug]='***'
  ##[debug]✔ secret/xxxx/xxx/xxxx => outputs.login | env.LOGIN
  ::endgroup::

*** Actual Output***
**Log Output**
##[debug]***
##[debug]***
##[debug]***
##[debug]***
##[debug]***
##[debug]***
##[debug]***
##[debug]***
##[debug]***
##[debug]***
##[debug]***
##[debug]***'
##[debug]Loading env
Run hashicorp/vault-action@master
  with:
    url: https://xxxx.xxxx
    token: ***
    caCertificate: ***
    secrets: secret/xxx/xxx/xxxx login
    method: token
    exportEnv: true
    tlsSkipVerify: false
::group::Get Vault Secrets
Get Vault Secrets
  ::endgroup::
##[error]Response code 404 (Not Found)
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Import Secrets

**Additional context**

**Comment by jasonodonnell** [comment]
This is likely an issue with the path to the secret.  There are differences between kvv1 and kvv2:

## KVV1
```
secrets: secret/foo login
```

### KVV2

```
secrets: secret/data/foo login
```

**Comment by prashant6475** [comment]
I get the same error :
Run hashicorp/vault-action@master
  with:
    url: https://xxx.xxx.xxx
    token: ***
    caCertificate: ***
    secrets: secret/data/xxxxx/test login
    method: token
    exportEnv: true
    tlsSkipVerify: false
::group::Get Vault Secrets
Get Vault Secrets
  ::endgroup::
##[error]Response code 404 (Not Found)

**Comment by jasonodonnell** [comment]
`404` means the secret at that path cannot be found.  Can you confirm that secret exists either using `vault` binary or `curl`?

```bash
$ vault read secret/data/xxxxxx/test
```

Additionally can you list your mount points?

```bash
$ vault secrets list -detailed
```

**Comment by prashant6475** [comment]
My problem is with kv2, same command you suggested works fine with kv1 but not with kv2.

Pasted the log outputs for both:
 
***for kv1: ***
$ vault read secret/xxxx/test/xxxx/
Key                 Value
---                 -----
refresh_interval    768h
login               xxxxx

*****for kv2 :*****

$ vault kv get secret/data/xxx/xxx/test/
====== Metadata ======
Key              Value
---              -----
created_time     xxxxxxxxxx
deletion_time    n/a
destroyed        false
version          2

==== Data ====
Key      Value
---      -----
login   xxxxx

vault read secret/data/xxxx/xxx/test/
WARNING! The following warnings were returned from Vault:

  * Invalid path for a versioned K/V secrets engine. See the API docs for the
  appropriate API endpoints to use. If using the Vault CLI, use 'vault kv get'
  for this operation.

**Comment by jasonodonnell** [comment]
Can you provide the output for:
```
vault secrets list -detailed
```

**Comment by prashant6475** [comment]
secret/data/xxxx/test/             kv          xxxxxxx           system         system     false             replicated     false        false                      map[version:2]    n/a                                                        xxxxxxxxxxxxxxxxxxxxx

**Comment by jasonodonnell** [comment]
I'm confused about your examples above.  You're reading secrets from `secret/`, which is a KVV2 secret engine.  KVV1 and KVV2 secret engines can't be mounted to the same path, so I'm wondering if we have a disconnect about versions.

Let's back up and start from scratch (assuming policies are correct for both of these):

### KVV1
```bash
vault secrets enable -path=secretkv1 -version=1 kv
vault kv put secretkv1/test foo=bar
vault read secretkv1/test
```

Our action should look like this:

```yaml
with:
  url: https://xxx.xxx.xxx
  token: ***
  caCertificate: ***
  secrets: secretkv1/test
  method: token
  exportEnv: true
```

### KVV2

```bash
vault secrets enable -path=secretkv2 -version=2 kv
vault kv put secretkv2/test foo=bar
vault read secretkv2/data/test
```

Our action should look like this:

```yaml
with:
  url: https://xxx.xxx.xxx
  token: ***
  caCertificate: ***
  secrets: secretkv2/data/test
  method: token
  exportEnv: true
```

**Comment by prashant6475** [comment]
I think we got the fix thanks for the suggestion.
