### ISSUE TITLE
[BUG] XML secret is incorrectly formatted by vault-action

### ISSUE THREAD

**Issue by BradenCTC** [hashicorp/vault-action#106]
**Describe the bug**
Storing XML (Azure function publish profile) that includes double quotes and $ characters as a secret results in incorrect formatting. Hashicorp/vault-action adds escape characters to publish profile (for every “ adds leading backslash) and it becomes for unrecognizable for Azure/functions-action:
![image](https://user-images.githubusercontent.com/68870992/91194412-1e086080-e6c6-11ea-896f-1e7e1c1cc8dd.png)

I then prepared in hashicorp a version for publish profile with leading and trailing single quotes, witch should prevent to  treat special characters as operators and take whole content as a string, and this is result:

![image](https://user-images.githubusercontent.com/68870992/91194648-57d96700-e6c6-11ea-9f75-61ea54017e8c.png)

username value should be: $odp-sandbox-cds-fn1, so part ‘$odp’ was just omitted – I think it was treated as a variable for some reason.

I tried a lot of other configurations, but without any success.

**To Reproduce**
Please see the above steps and images.

**Expected behavior**
The publish profile XML should be in the correct format

**Log Output**
Please see the output in the above images.

**Additional context**

**Comment by RichiCoder1** [comment]
I don't have an immediate ideas, but I wonder for this:

> username value should be: $odp-sandbox-cds-fn1, so part ‘$odp’ was just omitted – I think it was treated as a variable for some reason

if you aren't falling victim to bashes interpolation. Did you previous use the profile this was? Could you possible base64 the profile and then decode & use it where you need to? Or if it's being consumed by another action, you could use the outputs for to pass it directly: https://github.com/hashicorp/vault-action#set-output-variable-name

**Comment by BradenCTC** [comment]
Converting it to Base64 and back worked! Thanks!

**Comment by RichiCoder1** [comment]
Excellent!
