### ISSUE TITLE
[FEAT] `secrets.GITHUB_TOKEN` doesn't work with GitHub auth engine

### ISSUE THREAD

**Issue by ErikElkins** [hashicorp/vault-action#149]
**Is your feature request related to a problem? Please describe.**
`secrets.GITHUB_TOKEN` cannot be used to authenticate to the GitHub secrets engine.

**Describe the solution you'd like**
The `secrets.GITHUB_TOKEN` is able to be exchanged for a Vault token.

**Additional context**
It seems Vault wants to call `https://api.github.com/user` for the token that was passed to the auth engine. But the token isn't scoped to that API, and returns `GET https://api.github.com/user: 403 Resource not accessible by integration`.

**Comment by RichiCoder1** [comment]
The GitHub Workflow Token is not a real user token. It's a kind of magic GitHub token minted especially for action runs. So this will not work.

**Comment by ErikElkins** [comment]
So I guess this is a new feature request.  I'll update the issue.

**Comment by jasonodonnell** [comment]
@ErikElkins The repo "magic" token doesn't work with GitHub auth because you cannot change the permissions of the repo token to include org permissions (required). You will need to create a new GH secret that has a personal access token with org permissions. See our documentation for the auth method for more info: https://www.vaultproject.io/docs/auth/github

**Comment by steveteuber** [comment]
We also assumed that this is working, because the `${{ secrets.GITHUB_TOKEN }}` is used in the examples:

```
with:
  url: https://vault.mycompany.com:8200
  method: github
  githubToken: ${{ secrets.GITHUB_TOKEN }}
  caCertificate: ${{ secrets.VAULTCA }}
```

https://github.com/hashicorp/vault-action/blob/master/README.md#authentication-method

**Comment by jasonodonnell** [comment]
Updated the documentation with a notice for this: https://github.com/hashicorp/vault-action/pull/200

**Comment by jasonodonnell** [comment]
Closing since this is documented and a known limitation of Vault's GH auth method.
