### ISSUE TITLE
[FEAT] Support JWT auth

### ISSUE THREAD

**Issue by grascm** [hashicorp/vault-action#187]
**Is your feature request related to a problem? Please describe.**
The problem with current auth methods is permission management.
I am migrating from Gitlab to Github, and Gitlab has [built-it feature of generating JWT tokens](https://docs.gitlab.com/ee/ci/examples/authenticating-with-hashicorp-vault/#how-it-works).
Using this feature allowed me to write single policy for all my repos, and be sure, that every repo have access to only it's secrets:
```
path "gitlab-ci/data/{{identity.entity.aliases.auth_jwt_75ed0729.metadata.project_path}}" {
  capabilities = [ "read" ]
}
```

Now, only token and approle supported, and it forces me to manage unique secrets for every repo and manage all permissions manually (or give up, and allow every repo to read every secret for simplicity).

**Describe the solution you'd like**
Support for JWT auth method, where i can specify a key pair for token generation. Token with basic info about job would be generated to authenticate vault and get secrets

**Comment by GRascm** [comment]
Well i did it myself :)
https://github.com/hashicorp/vault-action/pull/188

**Comment by erickufrin** [comment]
Is there a good setup document that walks through ground-up configuration of JWT auth? I too am familiar with the GitLab implementation and am looking for how I can implement GitHub actions the the same type of auth.

**Comment by grascm** [comment]
@erickufrin

You need to generate JWT keys yourself, and put it to the secrets of you repository.
Also manually add public keys to vault. I've used python library `hvac` for this:
```
def read_file(filename):
    with open(filename, 'r') as f:
        return f.read()
        
client = hvac.Client(url=sys.argv[1], token=os.environ['VAULT_TOKEN'])
client.auth.jwt.configure(
    jwt_validation_pubkeys=read_file('jwt_validation_pubkeys.pem'),
    bound_issuer='vault-action')
```

After that, you can get you secrets, like in provided example:
```
with:
  url: https://vault.mycompany.com:8200
  method: jwt
  role: github-action
  jwtPrivateKey: ${{ secrets.JWT_PRIVATE_KEY }}
  jwtKeyPassword: ${{ secrets.JWT_KEY_PASS }}
  jwtTtl: 3600 # 1 hour, default value
```

Don't forget to setup jwt auth role `github-action`
