### ISSUE TITLE
Error in Github Vault Action : Input required and not supplied: secrets

### ISSUE THREAD

**Issue by vaporpin** [hashicorp/vault-action#192]
When using hashicorp/vault-action@v2.1.2, 

with:
  url: https://vault.mycompany.com:8200
  method: approle
  roleId: ${{ secrets.roleId }}
  secretId: ${{ secrets.secretId }}
  caCertificate: ${{ secrets.VAULTCA }}

I got the following error,  "Input required and not supplied: secrets"

Any advice on what the problem is?

**Comment by RichiCoder1** [comment]
I think you may be confused as to the purpose of this action?

Secrets is a required input as you have t specify what secrets you want to get from Vault: https://github.com/hashicorp/vault-action#example-usage

**Comment by vaporpin** [comment]
I see! thanks for your reply.
I was trying to get a secret from vault after enabling from secret engine GCP, however cannot find examples on it. I have a secret key"token" at path "gcp/token/terraform-gcp-roleset", I tried the entries below, but got an error "Error: unable to verify the first certificate". 

secrets: |
            /gcp/token/terraform-gcp-roleset token | GCP_TOKEN ;

May I ask if the error due to the certificate, "caCertificate: ${{ secrets.VAULTCA }}" ? 

Thanks for your advice.
