### ISSUE TITLE
Support for vault AWS Secrets Engine and similar?

### ISSUE THREAD

**Issue by jslusher** [hashicorp/vault-action#197]
**Is your feature request related to a problem? Please describe.**
Based on what I've read in the documentation, vault-action doesn't seem to support retrieving dynamics secrets for AWS Secrets Engine or the MySQL Secrets Engine. Am I reading that right?

**Describe the solution you'd like**
We want to use dynamic secrets for a distributed terraform setup, and having a GHA to use for it would be ideal.

**Describe alternatives you've considered**
At the moment I'm considering either figuring out a way to get GHA to accomplish this, or use static secrets.

**Comment by lomar92** [comment]
Hi is there any docs on how to use aws secret engine in vault action template?

**Comment by lomar92** [comment]
As this is closed. Could you provide a documentation on this?

I have a GHA for packer to create golden Images based on dynamically provided aws creds with Github oidc.

This is my config: 

permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    name: packer-build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Retrieve Secrets from HashiCorp Vault
        uses: hashicorp/vault-action@v2.4.0
        with:
          #Shared Runner needs public facing IP of HCP Vault        
          url: https://hcp-vault-cluster-public-vault-cbf7adf6.bd729d77.z1.hashicorp.cloud:8200
          exportToken: true
          namespace: admin
          method: jwt
          role: github-actions
          secrets: |
            cloud-secrets/data/hcp-secret HCP_CLIENT_ID | HCP_CLIENT_ID ;
            cloud-secrets/data/hcp-secret HCP_CLIENT_SECRET | HCP_CLIENT_SECRET ;
            /aws/creds/github-actions-aws access_key | access_key ;
            /aws/creds/github-actions-aws secret_key | secret_key
