### ISSUE TITLE
Deprecate `bjerkio/vault-action`

### ISSUE THREAD

**Issue by cobraz** [hashicorp/vault-action#203]
Hello 👋

Thank you for creating this Github Action!

Back in March of 2020, just when COVID-19 hit the world, I built `bjerkio/vault-action` as an alternative to `RichiCoder1/vault-action`. Now that RichiCoder1's implementation has become the official Github Action for Hashicorp Vault I want to evaluate if it's time to depreciate `bjerkio/vault-action`.

I'm thinking the best approach is to create a pinned issue in `bjerkio/vault-action` with a deprecation warning that includes a guide to how to instead use this Github Action. AFAIK, there are no features in `bjerkio/vault-action` that aren't implemented in `hashicorp/vault-action`. That probably becomes clear when creating a migration guide.

**Comment by cobraz** [comment]
I've created a deprecation notice now: https://github.com/bjerkio/vault-action/issues/393

**Comment by jasonodonnell** [comment]
Thanks for the heads up @cobraz!
