### ISSUE TITLE
When new version with  kubernetes auth will be released?

### ISSUE THREAD

**Issue by kirillbilchenko** [hashicorp/vault-action#229]
Hello, I would like to ask a question when the new version with  Kubernetes auth will be released?

**Comment by FalconerTC** [comment]
@jasonodonnell

**Comment by jasonodonnell** [comment]
Hi, this will be released next week. Hope that helps!

**Comment by jasonodonnell** [comment]
We actually had some spare time and were able to release this today. Enjoy 🎉
