### ISSUE TITLE
[FEAT] Allow user to specify output format or output in json by default

### ISSUE THREAD

**Issue by mpaduchh** [hashicorp/vault-action#236]
**Is your feature request related to a problem? Please describe.**
I would like to be able to retrieve all secrets from path formatted as JSON. This is possible with vault-cli and I think also with http request by specifying `-format=json`.
Right now I am accessing my secrets by doing this `path/to/secrets $.$`. What I get is space separated list of `key:value` pairs. Now, the problem is, my secrets can and contain both spaces and colons, so it is impossible to parse.

**Describe the solution you'd like**
I would like to be able to specify output format like in vault-cli OR I would like the default format to be something that can be parsed regardless of the data inside.  If you have an idea on how to solve this, parse the file to json I will be much obliged.

**Describe alternatives you've considered**
I tried parsing the output file with `jq` without success.

**Comment by slemme1** [comment]
There seems to be 3 common requests that get blurred together:
1) Retrieving all secrets in the path without having to specify keys
2) Formatting all secrets into json
3) Writing all secrets to a file in json format
Only 1) has no current solution.
You can already gather all outputs and get them into json  (and write to a file) outside of the vault-action step):
env:
    ALL_SECRETS_JSON: "${{ toJson(steps.vaultactionId.outputs) }}"

**Comment by maxcoulombe** [comment]
Hi, I agree with slemme1 that this issue encompasses 3 requests.

For n.2 & n.3, this has been discussed here: #98 . We believe that it is not the job of the vault-action to convert the retrieved secrets into multiple formats and that it is easy enough to convert and save the outputs in a json file in a subsequent step. Feel free to re-open the discussion in #98 if you do not agree with the conclusions and think the documentation enhancements are not enough.

For n.1, being able to retrieve all secrets in a path without using the $.$ work-around, there are quite a few issues an PRs opened to address this request including #238 .

If it's ok, I'll close this one as a duplicate so we can concentrate the discussion around supporting wildcards & regexes in the issues that already have a lot of context and comments. Cheers!
