### ISSUE TITLE
[FEAT]  Retrieve Lease ID

### ISSUE THREAD

**Issue by tkaburagi** [hashicorp/vault-action#250]
**Is your feature request related to a problem? Please describe.**
I would like to get the `lease_id` from `secrets`. Currently the only values under `.data.` could be set as variables. 

**Describe the solution you'd like**
I wanna revoke the dynamic secrets soon after completing jobs. I need to have `lease_id` to revoke. 

**Describe alternatives you've considered**
I tried search the values not in the `.data` but it's not successfull.

**Comment by smaeda-ks** [comment]
Hi @tkaburagi, Can I get a bit more clarification on this? Is this the case where users provide the persistent Vault token manually to the actions via GitHub Secrets, for instance (i.e., `token: ${{ secrets.VaultToken }}` is set)? and that they want to revoke individual secrets by each `lease_id`?

I think we should definitely discourage users from using this approach and migrate them over to other auth methods instead these days, especially GitHub Actions now support OIDC.

And for those other auth methods that obtain a client token dynamically upon workflow runs, the user will most likely revoke the client token as well, not just secrets when completing jobs, which can be done by one of those token revocation API endpoints below:
https://www.vaultproject.io/api-docs/auth/token#revoke-a-token-self

and by doing so, dynamic secrets associated with it will also be revoked automatically:

> When the token is revoked, all dynamic secrets generated with it are also revoked.

That said, wouldn't be enough to call the `POST /auth/token/revoke-self` endpoint with `exportToken` set to `true` in most cases?

```yaml
- name: Revoke tokens
    run: |
      curl -XPOST -sv -H "X-Vault-Token: ${{ env.VAULT_TOKEN }}" \
        https://https://vault.mycompany.com:8200/v1/auth/token/revoke-self
```

**Comment by tkaburagi** [comment]
Thanks! revoke self looks good.
