### ISSUE TITLE
[BUG] Last version doesn't refer to a major tag.

### ISSUE THREAD

**Issue by FrancoisXavierNoe** [hashicorp/vault-action#263]
**Describe the bug**
Last version (v2.3.1) doesn't refer to a major tag (v2).

**To Reproduce**
```
    steps:
      - uses: hashicorp/vault-action@v2
        ...
```

**Expected behavior**
Get the last version v2.3.1 when uses `hashicorp/vault-action@v2`.

**Log Output**
Error: Unable to resolve action `hashicorp/vault-action@v2`, unable to find version `v2`

**Additional context**
Hi there,
Is it possible to create/update a major tag (e.g. v2) when you create a tag for minor or patch version (e.g. v2.3.1) ?

Below an example:
![image](https://user-images.githubusercontent.com/41744606/136541863-83f1b7b4-48ac-4225-a1e7-c1fd5fa64575.png)

**Comment by netsandbox** [comment]
Here a link to the documentation where GitHub recommends using major version tags:
https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-tags-for-release-management

**Comment by FrancoisXavierNoe** [comment]
I see this documentation, and GitHub write :

> Move the major version tag (such as v1, v2) to point to the Git ref of the current release.

**Comment by tvoran** [comment]
Thanks for bringing this up! This makes sense to me; I'll see about getting it worked into our release process.

**Comment by tvoran** [comment]
This is now done. `hashicorp/vault-action@v2` should work in your workflows. We'll see about getting the readme updated too.

**Comment by netsandbox** [comment]
@tvoran sadly this is not fixed.
`v2.4.3` was released yesterday, but tag `v2` still points to `v2.4.2`.
Please update your release process.

**Comment by austingebauer** [comment]
@netsandbox - Sorry about that! We just updated the `v2` tag to point to `v2.4.3`.
