### ISSUE TITLE
[BUG] Unable to use the output/environment variables in the subsequent steps

### ISSUE THREAD

**Issue by venkkube** [hashicorp/vault-action#275]
**Describe the bug**
 I am unable to use the action outputs in the subsequent steps. I am seeing only `***` in printed in the log which is understandable due to masking, but if i export the values to text file i still see `***`.  From the logs i see the approle is authenticated successfully and received the token.
 Also secret path seems fine as i don't get any error from vault, but not sure why action isn't outputting the secret vaules.

**To Reproduce**
```
 - name: Import Vault Secrets
              id: pull_secrets
              uses: hashicorp/vault-action@v2.4.0
              with:
                url: https://enterprisevault.xxx:8200
                namespace: xxx
                method: approle
                roleId: ${{ secrets.TF_HASHICORP_VAULT_APPROLE_ID_DEV }}
                secretId: ${{ secrets.TF_HASHICORP_VAULT_SECRET_ID_DEV }}
                secrets: |
                    secrets/data/app/es/dev es-auth-token | ES_AUTH_TOKEN ;
                    secrets/data/app/es/dev es-cloud-user | ES_USER

            - name: Test
              id: test
              run: |
                echo "testing - ${{env.ES_USER}} " 
                echo ${{ steps.pull_secrets.outputs.ES_AUTH_TOKEN }} > test.txt
                cat test.txt
                echo "::set-output name=es_auth_token::${{ steps.pull_secrets.outputs.ES_AUTH_TOKEN }}"
```

**Expected behavior**
Should be able to use the action outputs in other steps/jobs in the workflow

**Log Output**
For the most verbose logs, [add a secret called `ACTIONS_STEP_DEBUG` with the value `true`](https://github.com/actions/toolkit/blob/master/docs/action-debugging.md). Then, re-run the workflow if possible and post the *raw logs* for the step here with any sensitive information masked or removed.
```
##[debug]Evaluating condition for step: 'Import Vault Secrets'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Import Vault Secrets
##[debug]Loading inputs
##[debug]Evaluating: secrets.TF_HASHICORP_VAULT_APPROLE_ID_DEV
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'TF_HASHICORP_VAULT_APPROLE_ID_DEV'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating: secrets.TF_HASHICORP_VAULT_SECRET_ID_DEV
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'TF_HASHICORP_VAULT_SECRET_ID_DEV'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Loading env
Run hashicorp/vault-action@v2.1.2
::group::Get Vault Secrets
Get Vault Secrets
Token Info
::add-mask::***
::add-mask::***
::set-output name=ES_AUTH_TOKEN::***
##[debug]steps.pull_secrets.outputs.ES_AUTH_TOKEN='***'
##[debug]✔ secrets/data/app/es/dev => outputs.ES_AUTH_TOKEN | env.ES_AUTH_TOKEN
##[debug]ℹ using cached response
::add-mask::***
::set-output name=ES_USER::***
##[debug]steps.pull_secrets.outputs.ES_USER='***'
##[debug]✔ secrets/data/app/es/dev => outputs.ES_USER | env.ES_USER
::endgroup::

##[debug]Node Action run completed with exit code 0
##[debug]VAULT_TOKEN='***'
##[debug]ES_AUTH_TOKEN='***'
##[debug]ES_USER='***'
##[debug]Finishing: Import Vault Secrets
```

** Next Step - Test **
```
Run echo "testing - *** " 
  echo "testing - *** " 
  echo *** > test.txt
  cat test.txt
  echo "::set-output name=es_auth_token::***"
  shell: /usr/bin/bash -e {0}
  env:
    DOMAIN: approval-dev.3dmanager.app
    SERVICE_NAME: approval-dev
    VAULT_TOKEN: ***
    ES_AUTH_TOKEN: ***
    ES_USER: ***
##[debug]/usr/bin/bash -e /opt/actions-runner/_work/_temp/2eb9467b-b5d7-4876-a506-114c9217138e.sh
testing - *** 
***
::set-output name=es_auth_token::***
##[debug]steps.test.outputs.es_auth_token='***'
##[debug]Finishing: Test
```

**Additional context**

**Comment by dwaragesh-balakrishnan** [comment]
Do we have any update on this one

**Comment by erickufrin** [comment]
Were you able to overcome this? I basically have hit a wall on passing retrieved secrets between steps and the lack of documentation on that makes it impossible to know if I am doing something wrong or what.

Is this legitimately a bug?  I am just trying to pass VAULT_TOKEN from the secrets retrieval step to subsequent steps where I will be making other calls to Vault using VAULT_TOKEN obtained during Secrets Retrieval step. I cant seem to get VAULT_TOKEN into subsequent steps even though I have set exportToken=true... UGH!

**Comment by dwaragesh-balakrishnan** [comment]
@erickufrin We had a similar problem with AWS credentials (IAM access and secret key) that Vault was creating and the workaround was to create a step and sleep for 10 seconds before using the credentials. Not sure if it will work for other use cases.

**Comment by WoodyWoodsta** [comment]
This is because Actions will mask _any_ output. Echo writes to the runner output, and this will be masked by Actions.

**Comment by waiyanwh** [comment]
I was also facing the exact same issue. Can't pass outputs to another steps.

**Comment by maxcoulombe** [comment]
Hi, all secrets retrieved from Vault are masked by the action so seeing the placeholder `***` when logging the secrets directly or via a file is expected.

Github Actions mask the _values_ not the _references_ so no matter the transformations (like writing into a file) you will never see the plain text value via Github (if you do please log a bug :smile: ).

Lets look at an example of how it works. Lets assume we have this secret in Vault:
```
vault kv put secret/test example=FOOBAR
```
And we use this action to retrieve it and try to print it out:
```
jobs:
  build:
    name: local-test
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@mcoulombe-test
        with:
          url: http://localhost:8200
          method: token
          token: root
          secrets: |
            secret/data/test example | EXAMPLE;
      - name: step following Import Secrets
        run: |
          echo Secret read from vault: "${{ env.EXAMPLE }}"
          echo Hardcoded string with the same value as the retrieved secret: FOOBAR
```

Because the plain text value of the secret in Vault is _FOOBAR_, the 2nd echo command that only outputs an hardcoded string will be obfuscated and shown as `***` even if it has no direct relation to the Vault secret. It simply happens to be the same value as what was masked so the output will be:
```
Secret read from vault: ***
Hardcoded string with the same value as the retrieved secret: ***
```

A PR #435 was recently merged to better explain how secrets can be used in subsequent steps. I believe from your description that what you are doing is correct and the outputs contain the correct value. They are simply obfuscated which can be misleading.

I'll close this issue since I do not think this is a bug in the vault-action. If you think I misunderstood something or the PR that enhanced the README with how to use outputs in subsequent steps is not sufficient for future users feel free to re-open the issue. Cheers!
