### ISSUE TITLE
[FEAT] Make `secrets` parameter optional so we can use this action just to get the token.

### ISSUE THREAD

**Issue by TomNorth** [hashicorp/vault-action#289]
**Is your feature request related to a problem? Please describe.**
The `secrets` parameter should not be mandatory. There is the option for `exportToken`, which is what I want to use to configure the Vault Terraform provider. However, with `secrets` being mandatory, it requires me to read a secret that I do not need. 

**Describe the solution you'd like**
The `secrets` parameter to not be mandatory, and allow us to use this action to simply get a Vault token to pass into other tooling.  

**Describe alternatives you've considered**
Honestly, none. Just grabbing a secret for the sake of using this action? I suppose I could create my own action that simply gets the token itself and posts to the login endpoint, but why not just use this one when it does the job?

**Additional context**
I am evaluating this action to use JWT with Github OIDC, as a potential replacement for internal automation around Vault access from CI. When configuring the Terraform Vault provider, you minimally need an endpoint, a token and, in our case, a namespace. I just want that sweet, sweet token. I don't wish to pass secrets into Terraform directly for example. It seems unnecessary to read a secret just to use this action to get a token.

**Comment by erickufrin** [comment]
+1. I want to make calls to Vault which are administering Vault - not retrieving secrets... I just need VAULT_TOKEN.

**Comment by elstak** [comment]
+1 Good to decouple authentication (get and populate VAULT_TOKEN) from fetching secrets, potentially multiple times, by reusing the same auth token.

**Comment by geolaz** [comment]
+1

**Comment by DmitryMihailov** [comment]
This action is almost perfect, but making the secrets fields mandatory wasn't needed...

**Comment by tcraxs** [comment]
Any process or release date for that? I really like to see that option in a released version 😄

**Comment by TomNorth** [comment]
Thanks @kevinschoonover for getting the PR in to enable this! 

@tomhjp  will we be getting a new release tag for this soon now that it has merged or do we have to wait for a cycle?

**Comment by tomhjp** [comment]
The next scheduled release is in a couple of weeks or so. If you're keen to use this before then I'd suggest [pinning to the latest SHA](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions) in the meantime.

**Comment by TomNorth** [comment]
@tomhjp just realised that won't work until the distribution is compiled.
