### ISSUE TITLE
[FEAT] Fetch all secrets in a given path

### ISSUE THREAD

**Issue by mangatmodi** [hashicorp/vault-action#292]
**Is your feature request related to a problem? Please describe.**
I have many secrets in a vault path. For now I have to add all of them. If we add more in the future, we will also need to add them in the pipeline definition to avail it.

**Describe the solution you'd like**
Perhaps we can specify only the vault paths. The variables from the subsequent path overwrite the first one. For e.g - 
```
path/to/a
path/to/b
```
Here variables from `path/to/b` will overwrite the same keys from `path/to/a`.  Obviously users can not specify name for them.

I would happy to contribute the pull request if the community agree.

**Comment by nenad** [comment]
This enhancement seems similar to https://github.com/hashicorp/vault-action/issues/234. A potential workaround might be https://github.com/hashicorp/vault-action/issues/153#issuecomment-824329289
