### ISSUE TITLE
[BUG] Issue when vault value contains $ or &

### ISSUE THREAD

**Issue by nitesh563** [hashicorp/vault-action#296]
**Describe the bug**
When the vault key vault contains ($ or &) it skip the characters after $ or &. 
For Example- If the key value is abc$xyz the vault action returns the value abc (skips $xyz).

**To Reproduce**
Use the vault action and include $ or & in vault key value.
Code: 
    - name: Vault Tokens
      uses: hashicorp/vault-action@version
      with:
        url: Vault URL
        method: approle
        roleId: RoleID
        secretId: SecretID
        secrets: |
          Secret_Path Vault_Key | Password
    - name: Echo Password
      run: echo ${{ env.Password }}

Add $ or & character in vault key value. 

**Expected behavior**
The vault action should return the entire vault key value including $ and &.

**Comment by joonvena** [comment]
I wouldn't say this is a bug as the output key is intentionally parsed and normalized here:
https://github.com/hashicorp/vault-action/blob/843e7fa30ad6b1b5c330f2bf0cade9c224a8ef44/src/action.js#L168

**Comment by fairclothjm** [comment]
@nitesh563 Can you please confirm if you are referring to the value of the **key** or the value of the **secret**?

I was not able to repro this with a test I added in #462. That test assumes the issue is with the secret value.

**Comment by fairclothjm** [comment]
Hi @nitesh563 as per the README:


> Note that the selector is using [JSONata](https://docs.jsonata.org/overview.html) and certain characters in keys may need to be escaped.
