### ISSUE TITLE
[BUG] Dependabot Alerts

### ISSUE THREAD

**Issue by aksmo** [hashicorp/vault-action#339]
**Describe the bug**
Looking to use in our enterprise, unfortunately looks like there are open vulnerabilities. There are open Dependabot Pars that are failing checks.

**To Reproduce**
Check Dependabot Alerts.

**Expected behavior**
All Dependabot issues must be fixed 

**Additional context**
We can't import any actions that have open vulnerabilities.

**Comment by tvoran** [comment]
Hi @aksmo, thanks for the reminder about dependency updates! Dependabot runs continuously on this repo and opens PRs for any dependency updates, though, and not just those that fix vulnerabilities.

And as a friendly reminder please report any security issues here responsibly by emailing [security@hashicorp.com](mailto:security@hashicorp.com).
