### ISSUE TITLE
Github actions integration error 

### ISSUE THREAD

**Issue by ankitaaswal9** [hashicorp/vault-action#364]
We are integrating vault with github action. We are getting the following error : 
<img width="456" alt="image" src="https://user-images.githubusercontent.com/85473259/190975456-9fe78e04-71a3-41d1-bb29-ae8435a687fd.png">

Below is the implementation code: 
` - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        id: secrets
        with:
            url: **url**
            tlsSkipVerify: true
            exportEnv: false
            secrets: secret/data/ci npmToken
            token: ${{ secrets.VAULT_TOKEN }}
            method: token
`

NOte: Our vault is behind VPN in kubernetes cluster.

**Comment by fairclothjm** [comment]
Due to inactivity, we will close this issue. Please feel free to reopen if you feel this was a mistake, or if there is additional information to add. Thanks!
