### ISSUE TITLE
[BUG] Upgrade to node 16

### ISSUE THREAD

**Issue by Ugzuzg** [hashicorp/vault-action#373]
**Describe the bug**

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: hashicorp/vault-action

**To Reproduce**
Just use the action in any way.

**Expected behavior**
Now deprecation warning shown.

**Comment by tvoran** [comment]
Thanks, this was addressed in #375, and will be out in the next release.
