### ISSUE TITLE
[FEAT] Support reading temporary database credentials

### ISSUE THREAD

**Issue by bimtauer** [hashicorp/vault-action#396]
**Is your feature request related to a problem? Please describe.**
If I understand correctly, this action is limited to KV stores and requires one to specific not only a path but also key to retrieve. 
For the [database secret engine](https://developer.hashicorp.com/vault/docs/secrets/databases) this creates a problem - here one would want to make a single request against Vault and return both the username and password not just either of them. 

It would be great if this action would support extracting all keys of a secret as json when providing `*` as a selector

**Describe the solution you'd like**
```yaml
secrets: |
  postgres/creds/foo * | DB_CREDS;
```
Results in the following json string to be stored in `DB_CREDS`: `{"username": "some-temp-username", "password": "some-temp-password"}`

**Current result**
selector gets wrapped into `data."*"` which doesn't work.

**Describe alternatives you've considered**
Writing my own raw get request to Vault

**Comment by bimtauer** [comment]
Anyone alive here?

**Comment by bimtauer** [comment]
@austingebauer sorry for the direct ping, we have a minimally invasive fix ready for this, could you have a look since you last contributed to this repo?

**Comment by fairclothjm** [comment]
Closing as this should be fixed by https://github.com/hashicorp/vault-action/pull/488.

Please feel free to reopen if you feel this was a mistake, or if there is additional information to add. Thanks!
