### ISSUE TITLE
[BUG] Undefined response object in getSecrets error handler

### ISSUE THREAD

**Issue by mldahl** [hashicorp/vault-action#432]
**Describe the bug**

The get request in `getSecrets` correctly throws an error if there is a self signed certificate in the certificate chain.  This error doesn't have a `response` property, so the 404 check throws with `Cannot read properties of undefined (reading 'statusCode')`

**To Reproduce**

id: secrets
uses: hashicorp/vault-action@v2
with:
  url: *removed*
  namespace: *removed*
  token: ${{ secrets.*removed* }}
  exportEnv: false
  secrets: |
    *removed* *removed*;

**Expected behavior**

Log output should read:
`Error: self signed certificate in certificate chain`

**Log Output**

`Error: Cannot read properties of undefined (reading 'statusCode')`

**Additional context**

https://github.com/hashicorp/vault-action/pull/431

**Comment by maxcoulombe** [comment]
Thanks for the report and the fix. The PR was merged and it will be part of the next release.
