### ISSUE TITLE
How to deal with the fact that vaults should be in a private network?

### ISSUE THREAD

**Issue by moltar** [hashicorp/vault-action#44]
Docs [state](https://learn.hashicorp.com/vault/operations/ops-deployment-guide#vault-ui):

> Vault should not be deployed in a public internet facing environment

How do you manage access to vault from GitHub Actions network?

From [GitHub Actions docs](https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#ip-addresses-of-github-hosted-runners), it seems to be using too many IPs to whitelist.

What is the security model that works best with GitHub Actions?

Thanks.

**Comment by RichiCoder1** [comment]
It's a good question, and one that I had an issue with myself! You've got a few options, but the ones that I identified as most reasonable for most people were:
1. Use GitHub Actions hosted runners to run it within your firewall. This assumes you have that capability and are fine loosing the out of the box runners and elasticity.
2. Setup a bastion box or other securely controlled endpoint, using something like certificate authentication or some other secure, rotatable method to authenticate. Then use SSH or some other proxy method to expose it to Vault Action. This is tantamount to exposing it to the internet, but you can use something like a reverse proxy to limit the available authentication methods and other paths that are exposes.

**Comment by Ameausoone** [comment]
It's possible to host self-host runners => https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#about-self-hosted-runners 
It's now even possible to host runners at organization level or even at Enterprise level.

**Comment by tcarrio** [comment]
You might also consider using a VPN such as Wireguard on the Vault host to connect these networks together. They otherwise remain private networks.

**Comment by jasonodonnell** [comment]
Closing since the question seems answered. Please feel free to reopen if you think this is a mistake!
