### ISSUE TITLE
SUPPORT FOR WRITE OPERATION (PERSISTENCE)

### ISSUE THREAD

**Issue by LatVAlY** [hashicorp/vault-action#498]
**Describe the need**
Does vault-action support write (persistence) operation or only read operation (retrieve)?

**Additional context**
'm trying to use the vault action to store secrets in the secret engine by providing a key, this way will allow me to automatically sync my secrets

**Comment by fairclothjm** [comment]
@LatVAlY Hello, yes vault-action only supports GET operations.

You may want to take a look at Secrets Sync for HCP or Vault Enterprise. HCP offers a free tier for secrets sync.

**Comment by fairclothjm** [comment]
Due to inactivity, we will close this issue. Please feel free to reopen if you feel this was a mistake, or if there is additional information to add. Thanks!
