### ISSUE TITLE
[BUG] The Vault action fails if the secret key contains a dot

### ISSUE THREAD

**Issue by AlexandarNaydenov** [hashicorp/vault-action#504]
## Vault server version
Vault 1.14.3 enterprise

## vault-action version
v2.7.4

## Describe the bug
The Vault Action fails if the secret key contains a dot. 
Example: `secret.token`

## To Reproduce
The yaml of the `vault-action` step:

```
steps:
      - name: Get Secrets from Vault
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault...
          namespace: some-namespace
          secrets: |
            kv/data/path/secret secret_token | SECRET_TOKEN1 ;
            kv/data/path/secret secret.token | SECRET_TOKEN2 ;
```

The first example with secret key `secret_token` works without problem, but ok the second one fails with an error log:
```
::error::Unable to retrieve result for data.data.secret.token. No match data was found. Double check your Key or Selector.
```

Screenshot of the Vault UI:

<img width="654" alt="Screenshot 2023-11-17 at 17 08 05" src="https://github.com/hashicorp/vault-action/assets/145471932/d936d96e-d579-45c3-ac7e-b28b064a8ec1">

## Expected behavior
To work with both secret keys.

**Comment by fairclothjm** [comment]
Hi @AlexandarNaydenov ! I am sorry you are having trouble. Can you try to use single quotes around the key?

```
          secrets: |
            kv/data/path/secret 'secret.token' | SECRET_TOKEN1 ;
```

I believe that should allow proper handling of the dot character.

**Comment by mourtallah** [comment]
I am dealing with a similar issue but with a space character instead of a dot.
...
          secrets: |
            kv/data/path/secret 'secret token' | SECRET_TOKEN1 ;
...
Should this work, or are spaces not allowed in the name of the secret token?
Should I make a new ticket for this? Or would should they have the same fix (I've tried wrapping it in single quotes as you recommended above but that didn't see to work, curious if it will for '.'

**Comment by andyspiers** [comment]
According to [the JSONata docs](https://docs.jsonata.org/simple), the correct character for quoting is the backtick

Have you tried:
```
`secret.token`
```
and
```
`secret token`
``` 
?

**Comment by fairclothjm** [comment]
Closing since @andyspiers's link to the JSONata docs seems to resolve the issue. https://docs.jsonata.org/simple

> Field references containing whitespace or reserved tokens can be enclosed in backticks


Please reopen an issue if you are still encountering trouble.
