### ISSUE TITLE
[BUG] Upgrade to node 20

### ISSUE THREAD

**Issue by bbarker-eb** [hashicorp/vault-action#524]
## Describe the bug
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: hashicorp/vault-action@v
For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

## To Reproduce
using the action in any way

## Expected behavior
No deprecation warning shown

**Comment by fairclothjm** [comment]
@bbarker-eb Hello, could you please provide the version of vault-action you are using? 

This was addressed in https://github.com/hashicorp/vault-action/pull/509 which was released as https://github.com/hashicorp/vault-action/releases/tag/v2.7.5 and available on the v2 tag https://github.com/hashicorp/vault-action/releases/tag/v2

See also:
https://github.com/hashicorp/vault-action/blob/9f522b85981b491eab9a52c144d15aedbd0bf371/action.yml#L97

**Comment by bbarker-eb** [comment]
2.4.3.  I had searched for a node20 in the release notes and was unable to find it.  Thank you!
