### ISSUE TITLE
[BUG] Node20 upgrade is backwards incompatible, but marked as patch version

### ISSUE THREAD

**Issue by cliffchapmanrbx** [hashicorp/vault-action#526]
Hi team,

The v2.7.5 version of this action [shipped a change bumping the required version of NodeJS to 20](https://github.com/hashicorp/vault-action/pull/517). This is a backwards-incompatible change, but was released as a patch version. This was unexpected and caused our workflows to start failing unexpectedly.

Our company has a contract with Hashicorp and we use GitHub Enterprise Server. GHES uses a different release cadence than GitHub Cloud, and our GHA runners are not compatible with Node20 yet. We have been impacted by several companies incorrectly marking these changes as patch versions, and they have graciously fixed the issue. We're currently working around the problem by pinning to version v2.7.4, however this is not ideal.

Can you please revert the v2.X version of the action to Node16 and release a new v3 version?

**Comment by fairclothjm** [comment]
@cliffchapmanrbx Thanks for bringing this to our attention. We are discussing this internally to see what we can do for a resolution.

**Comment by fairclothjm** [comment]
To resolve this we cut a new https://github.com/hashicorp/vault-action/releases/tag/v2.8.1 tag which is pointed to by https://github.com/hashicorp/vault-action/releases/tag/v2 for node 16.

Also, we cut https://github.com/hashicorp/vault-action/releases/tag/v3 for node20

**Comment by cliffchapmanrbx** [comment]
Fabulous, thank you so much!
