### ISSUE TITLE
HCP support

### ISSUE THREAD

**Issue by mihalt** [hashicorp/vault-action#538]
Hi! Can you give an example how to use HCP here? https://github.com/hashicorp/vault-action?tab=readme-ov-file#hashicorp-cloud-platform-or-vault-enterprise

As I see from instruction on HCP Vault website I should get token from https://auth.idp.hashicorp.com/oauth2/token with usage of HCP_CLIENT_ID and HCP_CLIENT_SECRET. And after get secrets from link https://api.cloud.hashicorp.com with usage of token. 

So, do you have this functionality?

**Comment by fairclothjm** [comment]
@mihalt Hello! You need the correct `url`, `namespeace`, and `token` set on the action and I think that should do it. What have you tried?

**Comment by mihalt** [comment]
> @mihalt Hello! You need the correct `url`, `namespeace`, and `token` set on the action and I think that should do it. What have you tried?

have you seen their url? it is something like 
`https://api.cloud.hashicorp.com/secrets/2023-06-13/organizations/.../projects/cf666bf8-4cfe-4545-95da-fd3fbd45cef3/apps/main-app/open`

And I should generate token each time. 

Also, I really don't understand what path should I use, that is required. 
And as I see from HCP manual, I don't need any of namespaces in request. I don't even see are they exist in it.

**Comment by fairclothjm** [comment]
@mihalt Hello, are you using HCP Vault or HCP Vault Secrets? [What is HCP Vault Secrets?](https://developer.hashicorp.com/hcp/docs/vault-secrets)

**Comment by mihalt** [comment]
> @mihalt Hello, are you using HCP Vault or HCP Vault Secrets? [What is HCP Vault Secrets?](https://developer.hashicorp.com/hcp/docs/vault-secrets)

looks like Vault Secrets. The link in browser like this https://portal.cloud.hashicorp.com/services/secrets/apps/
