### ISSUE TITLE
[FEAT] Output the vault secrets in a file

### ISSUE THREAD

**Issue by sylvainmouquet** [hashicorp/vault-action#98]
**Is your feature request related to a problem? Please describe.**
Currently we use GitLabCI and we export all keys of some paths in a json file. The arborescence in Vault is the same in the json file with a tree of keys. 

**Describe the solution you'd like**
The same feature with the GitHub actions
input: a list of path
output: a json with the key/values

**Describe alternatives you've considered**
No one

**Comment by jasonodonnell** [comment]
Hi @sylvainmouquet, we'll take a look at adding this feature.  In the mean time, contributions welcome!

**Comment by tcarrio** [comment]
@sylvainmouquet how do you expect this to be used? Will this be another way of calling the Vault CLI to output the JSON data?

An example use case may be useful for those who might be interested in implementing this feature.

I know it is possible to export secrets in JSON format using `vault read path/to/secret -format json`, for example.

**Comment by fean5959a** [comment]
Perhaps a solution may be to store the value of the key to a file. Usefull in some case if the value is a test file or a json.
Perhaps having a syntaxe like: 
secrets: secret/data/<my_secret> my_key | file://<file_where_to_write_value_ok_key>

**Comment by fean5959a** [comment]
Suggestion (because I work with sylvainmouquet):
I think it will be good (for this), to add 2 parameters:
- raw_output: (true|false)
- raw_output_file: </path/to/file>

"raw_output" keep initial json structure sent by Vault and actions provides it.
The goal is to provide a json structure like this:
`
{
  "<secret_1>":{
    "key_1": "value_1",
    "key_2": "value_2"
  },
  ...
}
`

If we specify keys, only them will be provide.
If we set "*" as key for a secret, all keys will be provide.
if "raw_output_file" is set, json will be write to file, instead output action will be set.

**Comment by RichiCoder1** [comment]
In theory `.` should also work for "get all". So a theoretical implementation could be:

```yaml
secrets: secret/data/key . > /tmp/secrets.json
```

With the `>` sigil signifying outputting to a file rather than an output variable.

**Comment by FalconerTC** [comment]
I'm interested in adding this, if there's still interest. Not sure which proposed solution would be better here though.

**Comment by romainvandecaveye** [comment]
i'm really interested by this..
Sorry, I meant I need this ! 
We are migrating from gitlab ci where you can just export a set of secret to a file, and we don't want to have to set all property manually

**Comment by slemme1** [comment]
I was going to open another enhancement request to read all secrets in the provided path without specifying each one in the secrets input:
Example: 
secrets:
    /secrets/myPath * | prefix   #get all secrets, using prefix+keyname as the output/env variable (or just keyname if no prefix).
Adding this feature would address the issue of setting secret names manually.
You can already gather all outputs and get them into json (and write to a file outside of the vault-action step):
env:
 ALL_SECRETS_JSON: "${{ toJson(steps.vaultaction.outputs) }}"

I think this enhancement would just take changes in secrets.js getSecrets():
if {request.selector = *), remove this request and add a new one for each key in the path (populating request.envVarName, request.outputVarName as appropriate if prefix is supplied).
I have not contributed to open source before and would be glad to take this on if I can get some mentoring on the process...

**Comment by mangatmodi** [comment]
Isn't it insecure? This enable people to cache/upload to artifacts. For now they only exist in variables in the runner process.

**Comment by minorgod** [comment]
Something like this would be very nice to have in situations where you work on a big team and ppl have not consistently named the vault paths so you end up with stuff scattered all over. I need to clean up a big vault such as this and it would be a huge help to be able to export everything under a given path (eg: /secrets/**/*) to a json file so I can see what the structure is, re-organize it, and then reimport it. Even if it only showed the path/key structure and obfuscated the actual secrets, it would still make my life easier. I'd love to see some sort of vault export/import that worked in json format. A "remap" or "migrate" feature might also be nice...something where you could dump the structure to json, then add some key/value such as "relocate-to": "/some/new/path" to a given path, then import it and it would move the paths to the new locations. Just brainstorming here.

**Comment by iamludal** [comment]
Up, still needing this. :)

**Comment by gabyfulchic** [comment]
Up, still needing this! :+1: 
Having an argument to output secrets in a file with a post task to clean them after a workflow run would be crazy!
If I can help too

**Comment by RichiCoder1** [comment]
I would also encourage closing this, but with the caveat that this should be documented to also avoid any questions in the future.

**Comment by slemme1** [comment]
My original need was to export all in a generic way without knowing the keys.  I uploaded the wilcard code in July 2021 but I don't think it made it to prod yet.  Is there something else that needs to be done?

**Comment by maxcoulombe** [comment]
@RichiCoder1 agreed, let me know if you think this modification to the README would answer this question fur future users:
https://github.com/hashicorp/vault-action/pull/435

@slemme1 I'm looking at the PRs and issues throughout the repo and I know there are a lot of demand for more flexibility around wildcards and regexes when retrieving secrets. I'm trying to consolidate all requests and proposed solutions to either approve or submit a PR that'd take care of all demands. No promise on the timeline but it seems like the most asked feature of the whole project so it's important to me that we reach a conclusion, it's been pending for a long time.
